.TH CHNETNS "1" "January 2018" "chnetns 0~20180117" "User Commands"
.SH NAME
\fIchnetns\fR \- run program in a named network namespace
.SH SYNOPSIS
chnetns <netns> <command> [<args>]
.SH DESCRIPTION
Run program in a specific named network namespace \fB<netns>\fR, very like to chroot.
.PP
Note: you may need root privileges for this.
