.TH NETNSINIT "1" "January 2018" "netnsinit 0~20180117" "User Commands"
.SH NAME
\fInetnsinit\fR \- configure named network namespace
.SH SYNOPSIS
netnsinit <network\-type> <ns\-name>
.SH DESCRIPTION
Auto configuration for \fBsystemd\-named\-netns\fR. Not intended for manual invocation.
.PP
Note: you may need root privileges for this.
