#!/bin/sh

display_usage() {
	echo "Run program in a specific named network namespace, very like to chroot."
	echo -e "\nUsage:\n\t$0 netns command [arguments] \n"
	echo "Note: you may need root privileges for this."
}

if [ $# = 0 ]; then
	display_usage
	exit 1
fi

case "$1" in
	"--help" | "-h")
		display_usage
		exit 0
		;;
	*)
	exec /bin/ip netns exec "$@"
	;;
esac
