#!/bin/bash

set -e

display_usage() {
	echo "Auto configuration for systemd-named-netns."
	echo -e "\nUsage:\n\t$0 network-type ns-name \n"
	echo "Note: you may need root privileges for this."
}

autoconfigure_tunnel() {
	[ ! -z "$MACADDR" ] && /bin/ip link set ${DEVNAME_INSIDE} address ${MACADDR}
	if [ "${DHCPV4}" == "1" ]; then
		! mkdir -p /var/run/netns
		dhclient -v -i ${DEVNAME_INSIDE} -nw -pf /var/run/netns/dhclient-${NSNAME}.pid
	else
		[ ! -z "${IPADDR}" ] && /bin/ip address add ${IPADDR} dev ${DEVNAME_INSIDE}
		[ ! -z "${GATEWAY}" ] && /bin/ip route add default via ${GATEWAY%%/*}
	fi
}

autoconfigure_nat() {
	# add default route if gateway undefined
	[ -z "${GATEWAY}" -a -n "${IPADDR_OUTSIDE}" ] && /bin/ip route add default via ${IPADDR_OUTSIDE%%/*}
}

autoconfigure() {
	local NSTYPE=$1
	local NSNAME=$2

	echo "Starting autoconfigure for $NSTYPE ${NSNAME}"
	DEVNAME_INSIDE=vn-${NSNAME}1
	source /etc/default/netns
	! source "/etc/default/netns-${NSNAME}"

	if type -t autoconfigure_$NSTYPE >/dev/null ; then
		autoconfigure_$NSTYPE "$@"
	fi

	echo "Autoconfiguration finished."
}

if [ $# == 0 ]; then
	display_usage
	exit 1
fi

case "$1" in
	"--help" | "-h")
		display_usage
		exit 0
		;;
	"tunnel"|"bridge"|"nat")
		autoconfigure "$@"
		exit 0
		;;
	*)
		echo "Unknown network type. Quitting."
		exit 1
		;;
esac
